[package]
name = "radvisor"
version = "0.1.0"
authors = ["Joseph Azevedo <joseph.az@gatech.edu>", "Bhanu Garg <bgarg6@gatech.edu>"]
edition = "2018"

[dependencies]
shiplift = "0.6"
tokio = "0.1"
bus = "2.2.3"
clap = { git = "https://github.com/clap-rs/clap/" }
ctrlc = { version = "3.0", features = ["termination"] }
