[package]
name = "radvisor"
version = "1.1.2"
authors = ["Joseph Azevedo <joseph.az@gatech.edu>", "Bhanu Garg <bgarg6@gatech.edu>"]
edition = "2018"

[dependencies]
shiplift = "0.6"
tokio = "0.2.13"
tokio-compat = { version = "0.1.5", features = ["rt-current-thread"] }
bus = "2.2.3"
csv = "1.1.3"
lazy_static = "1.4.0"
libc = "0.2.68"
gethostname = "0.2.1"
clap = { git = "https://github.com/clap-rs/clap/" }
numtoa = { git = "https://github.com/elba-kubernetes/numtoa/" }
ctrlc = { version = "3.0", features = ["termination"] }
kube = "0.30.0"
kube-derive = "0.30.0"
colored = "1.9.3"
lru_time_cache = "0.10.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
k8s-openapi = { version = "0.7.1", default-features = false, features = ["v1_15"] }

[dev-dependencies]
criterion = "0.3.1"
cargo-update = "3.0.0"

# Optimize bundle size on release compilation
[profile.release]
lto = true
codegen-units = 1

[[bench]]
name = "time_benchmark"
harness = false
